"""initial schema.

Revision ID: 001
Revises:
Create Date: 2026-03-25 08:02:06.473480

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "asset_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("idx_asset_types_name", "asset_types", ["name"], unique=False)
    op.create_index(
        "uq_asset_types_default",
        "asset_types",
        ["is_default"],
        unique=True,
        postgresql_where=sa.text("is_default = true"),
    )
    op.create_table(
        "data_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("adapter_type", sa.Text(), nullable=False),
        sa.Column("adapter_url", sa.Text(), nullable=False),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("token", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("idx_data_sources_name", "data_sources", ["name"], unique=False)
    op.create_table(
        "evaluation_batches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column(
            "trigger_params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "evaluation_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("rollup_details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_evaluation_batches_status", "evaluation_batches", ["status"], unique=False)
    op.create_table(
        "sli_definitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("adapter_type", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "comparable_from_version", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column(
            "indicators",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", name="uq_sli_name_version"),
    )
    op.create_index(
        "idx_sli_definitions_latest",
        "sli_definitions",
        ["name", sa.literal_column("version DESC")],
        unique=False,
    )
    op.create_index("idx_sli_definitions_name", "sli_definitions", ["name"], unique=False)
    op.create_table(
        "slo_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("template_slo_name", sa.Text(), nullable=False),
        sa.Column("template_slo_version", sa.Integer(), nullable=False),
        sa.Column(
            "gen_variables",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_slo_groups_name", "slo_groups", ["name"], unique=False)
    op.create_index(
        "uq_slo_groups_name_active",
        "slo_groups",
        ["name"],
        unique=True,
        postgresql_where=sa.text("active = true"),
    )
    op.create_table(
        "template_bindings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("target_type", sa.Text(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("template_group_name", sa.Text(), nullable=False),
        sa.Column("data_source_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "target_type IN ('asset', 'asset_group')", name="ck_template_bindings_target_type"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "target_type", "target_id", "template_group_name", name="uq_template_binding"
        ),
    )
    op.create_index(
        "idx_template_bindings_target",
        "template_bindings",
        ["target_type", "target_id"],
        unique=False,
    )
    op.create_table(
        "asset_group_links",
        sa.Column("parent_group_id", sa.UUID(), nullable=False),
        sa.Column("child_group_id", sa.UUID(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["child_group_id"], ["asset_groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_group_id"], ["asset_groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("parent_group_id", "child_group_id"),
    )
    op.create_index(
        "idx_asset_group_links_parent", "asset_group_links", ["parent_group_id"], unique=False
    )
    op.create_table(
        "asset_group_slo_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("link_name", sa.Text(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("slo_name", sa.Text(), nullable=False),
        sa.Column("sli_name", sa.Text(), nullable=False),
        sa.Column("data_source_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["group_id"], ["asset_groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "link_name", name="uq_asset_group_slo_link_name"),
        sa.UniqueConstraint("group_id", "slo_name", name="uq_asset_group_slo_link_group_slo"),
    )
    op.create_index(
        "idx_asset_group_slo_links_group", "asset_group_slo_links", ["group_id"], unique=False
    )
    op.create_table(
        "assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("type_name", sa.Text(), nullable=False),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "variables",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("heatmap_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["type_name"],
            ["asset_types.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "slo_bindings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("target_type", sa.Text(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("slo_name", sa.Text(), nullable=False),
        sa.Column("data_source_name", sa.Text(), nullable=False),
        sa.Column("comparison_rules", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source", sa.Text(), server_default=sa.text("'direct'"), nullable=False),
        sa.Column("template_binding_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "target_type IN ('asset', 'asset_group')", name="ck_slo_bindings_target_type"
        ),
        sa.ForeignKeyConstraint(
            ["template_binding_id"], ["template_bindings.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("target_type", "target_id", "slo_name", name="uq_slo_binding"),
    )
    op.create_index(
        "idx_slo_bindings_target", "slo_bindings", ["target_type", "target_id"], unique=False
    )
    op.create_table(
        "slo_definitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "comparable_from_version", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column(
            "total_score_pass_pct", sa.Float(), server_default=sa.text("90.0"), nullable=False
        ),
        sa.Column(
            "total_score_warning_pct", sa.Float(), server_default=sa.text("75.0"), nullable=False
        ),
        sa.Column(
            "comparison",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "variables",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("kind", sa.Text(), server_default=sa.text("'standard'"), nullable=False),
        sa.Column("sli_name", sa.Text(), nullable=True),
        sa.Column("sli_version", sa.Integer(), nullable=True),
        sa.Column("generated_by_group_id", sa.UUID(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["generated_by_group_id"],
            ["slo_groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", name="uq_slo_name_version"),
    )
    op.create_index(
        "idx_slo_definitions_latest",
        "slo_definitions",
        ["name", sa.literal_column("version DESC")],
        unique=False,
    )
    op.create_index("idx_slo_definitions_name", "slo_definitions", ["name"], unique=False)
    op.create_table(
        "asset_group_members",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["group_id"], ["asset_groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("group_id", "asset_id"),
    )
    op.create_index(
        "idx_asset_group_members_asset", "asset_group_members", ["asset_id"], unique=False
    )
    op.create_index(
        "idx_asset_group_members_group", "asset_group_members", ["group_id"], unique=False
    )
    op.create_table(
        "asset_slo_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("link_name", sa.Text(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("slo_name", sa.Text(), nullable=False),
        sa.Column("sli_name", sa.Text(), nullable=False),
        sa.Column("data_source_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "comparison_rules",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id", "link_name", name="uq_asset_slo_link_name"),
    )
    op.create_index("idx_asset_slo_links_asset", "asset_slo_links", ["asset_id"], unique=False)
    op.create_table(
        "evaluations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("evaluation_name", sa.Text(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column(
            "asset_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("slo_name", sa.Text(), nullable=False),
        sa.Column("slo_version", sa.Integer(), nullable=True),
        sa.Column("sli_name", sa.Text(), nullable=True),
        sa.Column("sli_version", sa.Integer(), nullable=True),
        sa.Column("data_source_name", sa.Text(), nullable=True),
        sa.Column(
            "variables",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("ingestion_mode", sa.Text(), nullable=False),
        sa.Column("adapter_used", sa.Text(), nullable=True),
        sa.Column("invalidated", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("invalidation_note", sa.Text(), nullable=True),
        sa.Column("baseline_pinned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("baseline_unpinned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("baseline_pin_reason", sa.Text(), nullable=True),
        sa.Column("baseline_pin_author", sa.Text(), nullable=True),
        sa.Column("original_result", sa.Text(), nullable=True),
        sa.Column("override_reason", sa.Text(), nullable=True),
        sa.Column("override_author", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "job_stats",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ingestion_mode IN ('pull','push','file')", name="ck_evaluations_ingestion_mode"
        ),
        sa.CheckConstraint(
            "result IN ('pass','warning','fail','error') OR result IS NULL",
            name="ck_evaluations_result",
        ),
        sa.CheckConstraint(
            "status IN ('pending','running','completed','failed','partial')",
            name="ck_evaluations_status",
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_evaluations_asset", "evaluations", ["asset_id"], unique=False)
    op.create_index(
        "idx_evaluations_baseline_lookup",
        "evaluations",
        ["asset_id", "slo_name", sa.literal_column("period_start DESC")],
        unique=False,
        postgresql_where=sa.text("status = 'completed' AND invalidated = false"),
    )
    op.create_index(
        "idx_evaluations_evaluation_name", "evaluations", ["evaluation_name"], unique=False
    )
    op.create_index("idx_evaluations_result", "evaluations", ["result"], unique=False)
    op.create_index("idx_evaluations_slo", "evaluations", ["slo_name", "slo_version"], unique=False)
    op.create_index("idx_evaluations_start", "evaluations", ["period_start"], unique=False)
    op.create_index("idx_evaluations_status", "evaluations", ["status"], unique=False)
    op.create_index(
        "idx_evaluations_stuck",
        "evaluations",
        ["status", "started_at"],
        unique=False,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_index(
        "uq_evaluations_identity",
        "evaluations",
        ["asset_id", "slo_name", "evaluation_name", "period_start", "period_end"],
        unique=True,
        postgresql_where=sa.text("status != 'failed'"),
    )
    op.create_table(
        "slo_objectives",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slo_definition_id", sa.UUID(), nullable=False),
        sa.Column("sli", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), server_default="", nullable=False),
        sa.Column("weight", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("key_sli", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "pass_criteria", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column(
            "warning_criteria", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("tab_group", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["slo_definition_id"], ["slo_definitions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_slo_objectives_definition", "slo_objectives", ["slo_definition_id"], unique=False
    )
    op.create_table(
        "evaluation_annotations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("evaluation_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("hidden_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hidden_by", sa.Text(), nullable=True),
        sa.Column("hidden_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["evaluation_id"], ["evaluations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_annotations_evaluation", "evaluation_annotations", ["evaluation_id"], unique=False
    )
    op.create_table(
        "indicator_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("evaluation_id", sa.UUID(), nullable=False),
        sa.Column("slo_objective_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("compared_value", sa.Float(), nullable=True),
        sa.Column("change_absolute", sa.Float(), nullable=True),
        sa.Column("change_relative_pct", sa.Float(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("score", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(["evaluation_id"], ["evaluations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["slo_objective_id"], ["slo_objectives.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "evaluation_id", "slo_objective_id", name="uq_indicator_results_eval_objective"
        ),
    )
    op.create_index(
        "idx_indicator_results_evaluation", "indicator_results", ["evaluation_id"], unique=False
    )
    op.create_index(
        "idx_indicator_results_objective_status",
        "indicator_results",
        ["slo_objective_id", "status"],
        unique=False,
    )
    op.create_table(
        "sli_values",
        sa.Column("eval_id", sa.UUID(), nullable=False),
        sa.Column("eval_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metric_name", sa.Text(), nullable=False),
        sa.Column("aggregation", sa.Text(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("asset_name", sa.Text(), nullable=True),
        sa.Column("evaluation_name", sa.Text(), nullable=True),
        sa.Column("os_tag", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["eval_id"],
            ["evaluations.id"],
        ),
        sa.PrimaryKeyConstraint("eval_id", "eval_start", "metric_name", "aggregation"),
    )
    op.create_index(
        "idx_sli_values_lookup",
        "sli_values",
        ["evaluation_name", "metric_name", "eval_start"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_sli_values_lookup", table_name="sli_values")
    op.drop_table("sli_values")
    op.drop_index("idx_indicator_results_objective_status", table_name="indicator_results")
    op.drop_index("idx_indicator_results_evaluation", table_name="indicator_results")
    op.drop_table("indicator_results")
    op.drop_index("idx_annotations_evaluation", table_name="evaluation_annotations")
    op.drop_table("evaluation_annotations")
    op.drop_index("idx_slo_objectives_definition", table_name="slo_objectives")
    op.drop_table("slo_objectives")
    op.drop_index(
        "uq_evaluations_identity",
        table_name="evaluations",
        postgresql_where=sa.text("status != 'failed'"),
    )
    op.drop_index(
        "idx_evaluations_stuck",
        table_name="evaluations",
        postgresql_where=sa.text("status = 'running'"),
    )
    op.drop_index("idx_evaluations_status", table_name="evaluations")
    op.drop_index("idx_evaluations_start", table_name="evaluations")
    op.drop_index("idx_evaluations_slo", table_name="evaluations")
    op.drop_index("idx_evaluations_result", table_name="evaluations")
    op.drop_index("idx_evaluations_evaluation_name", table_name="evaluations")
    op.drop_index(
        "idx_evaluations_baseline_lookup",
        table_name="evaluations",
        postgresql_where=sa.text("status = 'completed' AND invalidated = false"),
    )
    op.drop_index("idx_evaluations_asset", table_name="evaluations")
    op.drop_table("evaluations")
    op.drop_index("idx_asset_slo_links_asset", table_name="asset_slo_links")
    op.drop_table("asset_slo_links")
    op.drop_index("idx_asset_group_members_group", table_name="asset_group_members")
    op.drop_index("idx_asset_group_members_asset", table_name="asset_group_members")
    op.drop_table("asset_group_members")
    op.drop_index("idx_slo_definitions_name", table_name="slo_definitions")
    op.drop_index("idx_slo_definitions_latest", table_name="slo_definitions")
    op.drop_table("slo_definitions")
    op.drop_index("idx_slo_bindings_target", table_name="slo_bindings")
    op.drop_table("slo_bindings")
    op.drop_table("assets")
    op.drop_index("idx_asset_group_slo_links_group", table_name="asset_group_slo_links")
    op.drop_table("asset_group_slo_links")
    op.drop_index("idx_asset_group_links_parent", table_name="asset_group_links")
    op.drop_table("asset_group_links")
    op.drop_index("idx_template_bindings_target", table_name="template_bindings")
    op.drop_table("template_bindings")
    op.drop_index(
        "uq_slo_groups_name_active",
        table_name="slo_groups",
        postgresql_where=sa.text("active = true"),
    )
    op.drop_index("idx_slo_groups_name", table_name="slo_groups")
    op.drop_table("slo_groups")
    op.drop_index("idx_sli_definitions_name", table_name="sli_definitions")
    op.drop_index("idx_sli_definitions_latest", table_name="sli_definitions")
    op.drop_table("sli_definitions")
    op.drop_index("idx_evaluation_batches_status", table_name="evaluation_batches")
    op.drop_table("evaluation_batches")
    op.drop_index("idx_data_sources_name", table_name="data_sources")
    op.drop_table("data_sources")
    op.drop_index(
        "uq_asset_types_default",
        table_name="asset_types",
        postgresql_where=sa.text("is_default = true"),
    )
    op.drop_index("idx_asset_types_name", table_name="asset_types")
    op.drop_table("asset_types")
    op.drop_table("asset_groups")
    # ### end Alembic commands ###
