"""initial schema.

Revision ID: 001
Revises: 
Create Date: 2026-04-28 08:06:14.772956

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=False),
    sa.Column('show_on_graph', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('asset_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('asset_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_asset_types_name', 'asset_types', ['name'], unique=False)
    op.create_index('uq_asset_types_default', 'asset_types', ['is_default'], unique=True, postgresql_where=sa.text('is_default = true'))
    op.create_table('configuration',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('adapter_type', sa.Text(), nullable=False),
    sa.Column('adapter_url', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_data_sources_name', 'data_sources', ['name'], unique=False)
    op.create_table('sli_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('adapter_type', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('comparable_from_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('mode', sa.Text(), server_default=sa.text("'raw'"), nullable=False),
    sa.Column('query_template', sa.Text(), nullable=True),
    sa.Column('interval', sa.Text(), nullable=True),
    sa.Column('methods', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_sli_name_version')
    )
    op.create_index('idx_sli_definitions_latest', 'sli_definitions', ['name', sa.literal_column('version DESC')], unique=False)
    op.create_index('idx_sli_definitions_name', 'sli_definitions', ['name'], unique=False)
    op.create_table('slo_display_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['slo_display_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('slo_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('template_slo_definition_id', sa.UUID(), nullable=False),
    sa.Column('gen_variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_slo_definition_id'], ['slo_definitions.id'], name='fk_slo_groups_template_slo_definition_id', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_slo_groups_name', 'slo_groups', ['name'], unique=False)
    op.create_index('uq_slo_groups_name_active', 'slo_groups', ['name'], unique=True, postgresql_where=sa.text('active = true'))
    op.create_table('asset_group_links',
    sa.Column('parent_asset_group_id', sa.UUID(), nullable=False),
    sa.Column('child_asset_group_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['child_asset_group_id'], ['asset_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_asset_group_id'], ['asset_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_asset_group_id', 'child_asset_group_id')
    )
    op.create_index('idx_asset_group_links_parent', 'asset_group_links', ['parent_asset_group_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('type_name', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('heatmap_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['type_name'], ['asset_types.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('slo_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('comparable_from_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('total_score_pass_threshold', sa.Float(), server_default=sa.text('90.0'), nullable=False),
    sa.Column('total_score_warning_threshold', sa.Float(), server_default=sa.text('75.0'), nullable=False),
    sa.Column('comparison', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('kind', sa.Text(), server_default=sa.text("'standard'"), nullable=False),
    sa.Column('sli_definition_id', sa.UUID(), nullable=True),
    sa.Column('method_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_by_group_id', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_group_id'], ['slo_groups.id'], ),
    sa.ForeignKeyConstraint(['sli_definition_id'], ['sli_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_slo_name_version')
    )
    op.create_index('idx_slo_definitions_latest', 'slo_definitions', ['name', sa.literal_column('version DESC')], unique=False)
    op.create_index('idx_slo_definitions_name', 'slo_definitions', ['name'], unique=False)
    op.create_table('slo_display_group_members',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('slo_name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['slo_display_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'slo_name')
    )
    op.create_index('idx_slo_display_group_members_slo', 'slo_display_group_members', ['slo_name'], unique=False)
    op.create_table('asset_group_members',
    sa.Column('asset_group_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['asset_group_id'], ['asset_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_group_id', 'asset_id')
    )
    op.create_index('idx_asset_group_members_asset', 'asset_group_members', ['asset_id'], unique=False)
    op.create_index('idx_asset_group_members_group', 'asset_group_members', ['asset_group_id'], unique=False)
    op.create_table('asset_meta_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_asset_meta_snapshots_asset_observed', 'asset_meta_snapshots', ['asset_id', 'observed_at'], unique=False)
    op.create_index('idx_asset_meta_snapshots_asset_source_observed', 'asset_meta_snapshots', ['asset_id', 'source', 'observed_at'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('eval_name', sa.Text(), nullable=False),
    sa.Column('compare_to', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('achieved_points', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("result IN ('pass','warning','fail','error') OR result IS NULL", name='ck_evaluations_result'),
    sa.CheckConstraint("status IN ('pending','running','completed','failed')", name='ck_evaluations_status'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evaluations_asset', 'evaluations', ['asset_id'], unique=False)
    op.create_index('idx_evaluations_incomplete_period_end', 'evaluations', ['period_end'], unique=False, postgresql_where=sa.text("status != 'completed'"))
    op.create_index('idx_evaluations_period', 'evaluations', ['asset_id', sa.literal_column('period_start DESC')], unique=False)
    op.create_index('idx_evaluations_status', 'evaluations', ['status'], unique=False)
    op.create_table('slo_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('asset_group_id', sa.UUID(), nullable=True),
    sa.Column('slo_definition_id', sa.UUID(), nullable=False),
    sa.Column('slo_name', sa.Text(), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('comparison_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(asset_id IS NULL) != (asset_group_id IS NULL)', name='ck_slo_assignments_target'),
    sa.ForeignKeyConstraint(['asset_group_id'], ['asset_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['slo_definition_id'], ['slo_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_slo_assignments_asset', 'slo_assignments', ['asset_id'], unique=False)
    op.create_index('idx_slo_assignments_group', 'slo_assignments', ['asset_group_id'], unique=False)
    op.create_index('uq_slo_assignments_asset_slo', 'slo_assignments', ['asset_id', 'slo_name'], unique=True, postgresql_where=sa.text('asset_id IS NOT NULL'))
    op.create_index('uq_slo_assignments_group_slo', 'slo_assignments', ['asset_group_id', 'slo_name'], unique=True, postgresql_where=sa.text('asset_group_id IS NOT NULL'))
    op.create_table('slo_group_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('asset_group_id', sa.UUID(), nullable=True),
    sa.Column('slo_group_id', sa.UUID(), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(asset_id IS NULL) != (asset_group_id IS NULL)', name='ck_slo_group_assignments_target'),
    sa.ForeignKeyConstraint(['asset_group_id'], ['asset_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['slo_group_id'], ['slo_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_slo_group_assignments_asset', 'slo_group_assignments', ['asset_id'], unique=False)
    op.create_index('idx_slo_group_assignments_asset_group', 'slo_group_assignments', ['asset_group_id'], unique=False)
    op.create_index('uq_slo_group_assignments_asset', 'slo_group_assignments', ['asset_id', 'slo_group_id'], unique=True, postgresql_where=sa.text('asset_id IS NOT NULL'))
    op.create_index('uq_slo_group_assignments_group', 'slo_group_assignments', ['asset_group_id', 'slo_group_id'], unique=True, postgresql_where=sa.text('asset_group_id IS NOT NULL'))
    op.create_table('slo_objectives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slo_definition_id', sa.UUID(), nullable=False),
    sa.Column('sli', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), server_default='', nullable=False),
    sa.Column('weight', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('key_sli', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('pass_threshold', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('warning_threshold', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('tab_group', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['slo_definition_id'], ['slo_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_slo_objectives_definition', 'slo_objectives', ['slo_definition_id'], unique=False)
    op.create_table('asset_meta_closures',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.ARRAY(sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['asset_meta_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'path', name='uq_asset_meta_closures_snapshot_path')
    )
    op.create_index('idx_asset_meta_closures_snapshot', 'asset_meta_closures', ['snapshot_id'], unique=False)
    op.create_table('asset_meta_values',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['asset_meta_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'path', name='uq_asset_meta_values_snapshot_path')
    )
    op.create_index('idx_asset_meta_values_snapshot', 'asset_meta_values', ['snapshot_id'], unique=False)
    op.create_table('change_point_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slo_objective_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('higher_is_better', sa.Boolean(), nullable=False),
    sa.Column('window_size', sa.Integer(), nullable=False),
    sa.Column('max_pvalue', sa.Float(), nullable=False),
    sa.Column('min_magnitude', sa.Float(), nullable=False),
    sa.Column('min_sample_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['slo_objective_id'], ['slo_objectives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slo_objective_id')
    )
    op.create_table('slo_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('evaluation_name', sa.Text(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('asset_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('achieved_points', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('slo_name', sa.Text(), nullable=False),
    sa.Column('slo_version', sa.Integer(), nullable=True),
    sa.Column('sli_name', sa.Text(), nullable=True),
    sa.Column('sli_version', sa.Integer(), nullable=True),
    sa.Column('data_source_name', sa.Text(), nullable=True),
    sa.Column('slo_definition_id', sa.UUID(), nullable=True),
    sa.Column('sli_definition_id', sa.UUID(), nullable=True),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('ingestion_mode', sa.Text(), nullable=False),
    sa.Column('adapter_used', sa.Text(), nullable=True),
    sa.Column('invalidated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('invalidation_note', sa.Text(), nullable=True),
    sa.Column('baseline_pinned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('baseline_unpinned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('baseline_pin_reason', sa.Text(), nullable=True),
    sa.Column('baseline_pin_author', sa.Text(), nullable=True),
    sa.Column('original_result', sa.Text(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('override_author', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('job_stats', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("ingestion_mode IN ('pull','push','file')", name='ck_slo_evaluations_ingestion_mode'),
    sa.CheckConstraint("result IN ('pass','warning','fail','error') OR result IS NULL", name='ck_slo_evaluations_result'),
    sa.CheckConstraint("status IN ('pending','running','completed','failed','partial')", name='ck_slo_evaluations_status'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sli_definition_id'], ['sli_definitions.id'], ),
    sa.ForeignKeyConstraint(['slo_definition_id'], ['slo_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_slo_evaluations_asset', 'slo_evaluations', ['asset_id'], unique=False)
    op.create_index('idx_slo_evaluations_baseline_lookup', 'slo_evaluations', ['asset_id', 'slo_name', sa.literal_column('period_start DESC')], unique=False, postgresql_where=sa.text("status = 'completed' AND invalidated = false"))
    op.create_index('idx_slo_evaluations_evaluation_name', 'slo_evaluations', ['evaluation_name'], unique=False)
    op.create_index('idx_slo_evaluations_result', 'slo_evaluations', ['result'], unique=False)
    op.create_index('idx_slo_evaluations_slo', 'slo_evaluations', ['slo_name', 'slo_version'], unique=False)
    op.create_index('idx_slo_evaluations_start', 'slo_evaluations', ['period_start'], unique=False)
    op.create_index('idx_slo_evaluations_status', 'slo_evaluations', ['status'], unique=False)
    op.create_index('idx_slo_evaluations_stuck', 'slo_evaluations', ['status', 'started_at'], unique=False, postgresql_where=sa.text("status = 'running'"))
    op.create_index('uq_slo_evaluations_identity', 'slo_evaluations', ['asset_id', 'slo_name', 'evaluation_name', 'period_start', 'period_end'], unique=True, postgresql_where=sa.text("status != 'failed'"))
    op.create_table('evaluation_annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slo_evaluation_id', sa.UUID(), nullable=True),
    sa.Column('evaluation_run_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('note_group_id', sa.UUID(), nullable=True),
    sa.Column('note_group_name', sa.Text(), nullable=True),
    sa.Column('hidden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hidden_by', sa.Text(), nullable=True),
    sa.Column('hidden_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(slo_evaluation_id IS NULL) <> (evaluation_run_id IS NULL)', name='ck_annotation_exactly_one_parent'),
    sa.ForeignKeyConstraint(['category_id'], ['annotation_categories.id'], ),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slo_evaluation_id'], ['slo_evaluations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_annotations_evaluation_run', 'evaluation_annotations', ['evaluation_run_id'], unique=False)
    op.create_index('idx_annotations_slo_evaluation', 'evaluation_annotations', ['slo_evaluation_id'], unique=False)
    op.create_index(op.f('ix_evaluation_annotations_note_group_id'), 'evaluation_annotations', ['note_group_id'], unique=False)
    op.create_table('indicator_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slo_evaluation_id', sa.UUID(), nullable=False),
    sa.Column('slo_objective_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('compared_value', sa.Float(), nullable=True),
    sa.Column('change_absolute', sa.Float(), nullable=True),
    sa.Column('change_relative_pct', sa.Float(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('targets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['slo_evaluation_id'], ['slo_evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slo_objective_id'], ['slo_objectives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slo_evaluation_id', 'slo_objective_id', name='uq_indicator_results_eval_objective')
    )
    op.create_index('idx_indicator_results_objective_status', 'indicator_results', ['slo_objective_id', 'status'], unique=False)
    op.create_index('idx_indicator_results_slo_evaluation', 'indicator_results', ['slo_evaluation_id'], unique=False)
    op.create_table('sli_values',
    sa.Column('slo_evaluation_id', sa.UUID(), nullable=False),
    sa.Column('eval_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_name', sa.Text(), nullable=False),
    sa.Column('aggregation', sa.Text(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('asset_name', sa.Text(), nullable=True),
    sa.Column('evaluation_name', sa.Text(), nullable=True),
    sa.Column('os_tag', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['slo_evaluation_id'], ['slo_evaluations.id'], ),
    sa.PrimaryKeyConstraint('slo_evaluation_id', 'eval_start', 'metric_name', 'aggregation')
    )
    op.create_index('idx_sli_values_lookup', 'sli_values', ['evaluation_name', 'metric_name', 'eval_start'], unique=False)
    op.create_table('change_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indicator_result_id', sa.UUID(), nullable=True),
    sa.Column('evaluation_run_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('slo_name', sa.Text(), nullable=False),
    sa.Column('metric_name', sa.Text(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detector', sa.Text(), server_default=sa.text("'e_divisive'"), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('change_relative_pct', sa.Float(), nullable=False),
    sa.Column('change_absolute', sa.Float(), nullable=False),
    sa.Column('t_statistic', sa.Float(), nullable=False),
    sa.Column('pre_segment_mean', sa.Float(), nullable=False),
    sa.Column('post_segment_mean', sa.Float(), nullable=False),
    sa.Column('post_segment_std', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'unprocessed'"), nullable=False),
    sa.Column('triage_author', sa.Text(), nullable=True),
    sa.Column('triage_note', sa.Text(), nullable=True),
    sa.Column('triage_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('linked_ticket', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['indicator_result_id'], ['indicator_results.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_change_points_created', 'change_points', ['created_at'], unique=False)
    op.create_index('idx_change_points_identity', 'change_points', ['asset_id', 'slo_name', 'metric_name', 'period_start'], unique=False)
    op.create_index('idx_change_points_indicator', 'change_points', ['indicator_result_id'], unique=False)
    op.create_index('idx_change_points_run', 'change_points', ['evaluation_run_id', 'metric_name', 'period_start'], unique=False)
    op.create_index('idx_change_points_unprocessed', 'change_points', ['status'], unique=False, postgresql_where=sa.text("status = 'unprocessed'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_change_points_unprocessed', table_name='change_points', postgresql_where=sa.text("status = 'unprocessed'"))
    op.drop_index('idx_change_points_run', table_name='change_points')
    op.drop_index('idx_change_points_indicator', table_name='change_points')
    op.drop_index('idx_change_points_identity', table_name='change_points')
    op.drop_index('idx_change_points_created', table_name='change_points')
    op.drop_table('change_points')
    op.drop_index('idx_sli_values_lookup', table_name='sli_values')
    op.drop_table('sli_values')
    op.drop_index('idx_indicator_results_slo_evaluation', table_name='indicator_results')
    op.drop_index('idx_indicator_results_objective_status', table_name='indicator_results')
    op.drop_table('indicator_results')
    op.drop_index(op.f('ix_evaluation_annotations_note_group_id'), table_name='evaluation_annotations')
    op.drop_index('idx_annotations_slo_evaluation', table_name='evaluation_annotations')
    op.drop_index('idx_annotations_evaluation_run', table_name='evaluation_annotations')
    op.drop_table('evaluation_annotations')
    op.drop_index('uq_slo_evaluations_identity', table_name='slo_evaluations', postgresql_where=sa.text("status != 'failed'"))
    op.drop_index('idx_slo_evaluations_stuck', table_name='slo_evaluations', postgresql_where=sa.text("status = 'running'"))
    op.drop_index('idx_slo_evaluations_status', table_name='slo_evaluations')
    op.drop_index('idx_slo_evaluations_start', table_name='slo_evaluations')
    op.drop_index('idx_slo_evaluations_slo', table_name='slo_evaluations')
    op.drop_index('idx_slo_evaluations_result', table_name='slo_evaluations')
    op.drop_index('idx_slo_evaluations_evaluation_name', table_name='slo_evaluations')
    op.drop_index('idx_slo_evaluations_baseline_lookup', table_name='slo_evaluations', postgresql_where=sa.text("status = 'completed' AND invalidated = false"))
    op.drop_index('idx_slo_evaluations_asset', table_name='slo_evaluations')
    op.drop_table('slo_evaluations')
    op.drop_table('change_point_config')
    op.drop_index('idx_asset_meta_values_snapshot', table_name='asset_meta_values')
    op.drop_table('asset_meta_values')
    op.drop_index('idx_asset_meta_closures_snapshot', table_name='asset_meta_closures')
    op.drop_table('asset_meta_closures')
    op.drop_index('idx_slo_objectives_definition', table_name='slo_objectives')
    op.drop_table('slo_objectives')
    op.drop_index('uq_slo_group_assignments_group', table_name='slo_group_assignments', postgresql_where=sa.text('asset_group_id IS NOT NULL'))
    op.drop_index('uq_slo_group_assignments_asset', table_name='slo_group_assignments', postgresql_where=sa.text('asset_id IS NOT NULL'))
    op.drop_index('idx_slo_group_assignments_asset_group', table_name='slo_group_assignments')
    op.drop_index('idx_slo_group_assignments_asset', table_name='slo_group_assignments')
    op.drop_table('slo_group_assignments')
    op.drop_index('uq_slo_assignments_group_slo', table_name='slo_assignments', postgresql_where=sa.text('asset_group_id IS NOT NULL'))
    op.drop_index('uq_slo_assignments_asset_slo', table_name='slo_assignments', postgresql_where=sa.text('asset_id IS NOT NULL'))
    op.drop_index('idx_slo_assignments_group', table_name='slo_assignments')
    op.drop_index('idx_slo_assignments_asset', table_name='slo_assignments')
    op.drop_table('slo_assignments')
    op.drop_index('idx_evaluations_status', table_name='evaluations')
    op.drop_index('idx_evaluations_period', table_name='evaluations')
    op.drop_index('idx_evaluations_incomplete_period_end', table_name='evaluations', postgresql_where=sa.text("status != 'completed'"))
    op.drop_index('idx_evaluations_asset', table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index('idx_asset_meta_snapshots_asset_source_observed', table_name='asset_meta_snapshots')
    op.drop_index('idx_asset_meta_snapshots_asset_observed', table_name='asset_meta_snapshots')
    op.drop_table('asset_meta_snapshots')
    op.drop_index('idx_asset_group_members_group', table_name='asset_group_members')
    op.drop_index('idx_asset_group_members_asset', table_name='asset_group_members')
    op.drop_table('asset_group_members')
    op.drop_index('idx_slo_display_group_members_slo', table_name='slo_display_group_members')
    op.drop_table('slo_display_group_members')
    op.drop_index('idx_slo_definitions_name', table_name='slo_definitions')
    op.drop_index('idx_slo_definitions_latest', table_name='slo_definitions')
    op.drop_table('slo_definitions')
    op.drop_table('assets')
    op.drop_index('idx_asset_group_links_parent', table_name='asset_group_links')
    op.drop_table('asset_group_links')
    op.drop_index('uq_slo_groups_name_active', table_name='slo_groups', postgresql_where=sa.text('active = true'))
    op.drop_index('idx_slo_groups_name', table_name='slo_groups')
    op.drop_table('slo_groups')
    op.drop_table('slo_display_groups')
    op.drop_index('idx_sli_definitions_name', table_name='sli_definitions')
    op.drop_index('idx_sli_definitions_latest', table_name='sli_definitions')
    op.drop_table('sli_definitions')
    op.drop_index('idx_data_sources_name', table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_table('configuration')
    op.drop_index('uq_asset_types_default', table_name='asset_types', postgresql_where=sa.text('is_default = true'))
    op.drop_index('idx_asset_types_name', table_name='asset_types')
    op.drop_table('asset_types')
    op.drop_table('asset_groups')
    op.drop_table('annotation_categories')
    # ### end Alembic commands ###
