"""Initial schema: assets, slo_definitions, evaluations, annotations, sli_values hypertable.

Revision ID: 001
Revises: initial
Create Date: 2026-03-13 23:28:05.415958

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "slo_definitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("slo_yaml", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", name="uq_slo_name_version"),
    )
    op.create_index(
        "idx_slo_definitions_latest",
        "slo_definitions",
        ["name", sa.literal_column("version DESC")],
        unique=False,
    )
    op.create_index("idx_slo_definitions_name", "slo_definitions", ["name"], unique=False)
    op.create_table(
        "evaluations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=True),
        sa.Column(
            "asset_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("slo_yaml", sa.Text(), nullable=True),
        sa.Column("slo_name", sa.Text(), nullable=True),
        sa.Column("slo_version", sa.Integer(), nullable=True),
        sa.Column(
            "indicator_results",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "evaluation_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("ingestion_mode", sa.Text(), nullable=False),
        sa.Column("adapter_used", sa.Text(), nullable=True),
        sa.Column("invalidated", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("invalidation_note", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "job_stats",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ingestion_mode IN ('pull','push','file')", name="ck_evaluations_ingestion_mode"
        ),
        sa.CheckConstraint(
            "result IN ('pass','warning','fail','error') OR result IS NULL",
            name="ck_evaluations_result",
        ),
        sa.CheckConstraint(
            "status IN ('pending','running','completed','failed','partial')",
            name="ck_evaluations_status",
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_evaluations_asset", "evaluations", ["asset_id"], unique=False)
    op.create_index("idx_evaluations_name", "evaluations", ["name"], unique=False)
    op.create_index("idx_evaluations_result", "evaluations", ["result"], unique=False)
    op.create_index("idx_evaluations_slo", "evaluations", ["slo_name", "slo_version"], unique=False)
    op.create_index("idx_evaluations_start", "evaluations", ["start_time"], unique=False)
    op.create_index("idx_evaluations_status", "evaluations", ["status"], unique=False)
    op.create_index(
        "idx_evaluations_stuck",
        "evaluations",
        ["status", "started_at"],
        unique=False,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_table(
        "evaluation_annotations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("evaluation_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["evaluation_id"], ["evaluations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_annotations_evaluation", "evaluation_annotations", ["evaluation_id"], unique=False
    )
    op.create_table(
        "sli_values",
        sa.Column("eval_id", sa.UUID(), nullable=False),
        sa.Column("eval_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metric_name", sa.Text(), nullable=False),
        sa.Column("aggregation", sa.Text(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("asset_name", sa.Text(), nullable=True),
        sa.Column("test_name", sa.Text(), nullable=True),
        sa.Column("os_tag", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["eval_id"],
            ["evaluations.id"],
        ),
        sa.PrimaryKeyConstraint("eval_id", "eval_start", "metric_name", "aggregation"),
    )
    op.create_index(
        "idx_sli_values_lookup",
        "sli_values",
        ["test_name", "metric_name", "eval_start"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_sli_values_lookup", table_name="sli_values")
    op.drop_table("sli_values")
    op.drop_index("idx_annotations_evaluation", table_name="evaluation_annotations")
    op.drop_table("evaluation_annotations")
    op.drop_index(
        "idx_evaluations_stuck",
        table_name="evaluations",
        postgresql_where=sa.text("status = 'running'"),
    )
    op.drop_index("idx_evaluations_status", table_name="evaluations")
    op.drop_index("idx_evaluations_start", table_name="evaluations")
    op.drop_index("idx_evaluations_slo", table_name="evaluations")
    op.drop_index("idx_evaluations_result", table_name="evaluations")
    op.drop_index("idx_evaluations_name", table_name="evaluations")
    op.drop_index("idx_evaluations_asset", table_name="evaluations")
    op.drop_table("evaluations")
    op.drop_index("idx_slo_definitions_name", table_name="slo_definitions")
    op.drop_index("idx_slo_definitions_latest", table_name="slo_definitions")
    op.drop_table("slo_definitions")
    op.drop_table("assets")
    # ### end Alembic commands ###
