"""TimescaleDB hypertable and seed data.

Revision ID: 002
Revises: 001
Create Date: 2026-03-15 20:40:59.384949

Manual migration — not autogenerated.
Converts sli_values to a TimescaleDB hypertable and seeds default asset types
and change point detection defaults.
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: str | Sequence[str] | None = '001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Convert sli_values to a TimescaleDB hypertable partitioned by eval_start.
    # if_not_exists=TRUE makes this safe to re-run.
    op.execute("SELECT create_hypertable('sli_values', 'eval_start', if_not_exists => TRUE)")

    # Seed default asset types.
    # ON CONFLICT DO NOTHING so re-running this migration is idempotent.
    op.execute("""
        INSERT INTO asset_types (id, name, is_default) VALUES
            (gen_random_uuid(), 'vm',        true),
            (gen_random_uuid(), 'service',   false),
            (gen_random_uuid(), 'database',  false),
            (gen_random_uuid(), 'container', false),
            (gen_random_uuid(), 'endpoint',  false),
            (gen_random_uuid(), 'load-test', false)
        ON CONFLICT (name) DO NOTHING
    """)

    # Seed default annotation categories.
    # ON CONFLICT DO NOTHING so re-running this migration is idempotent.
    op.execute("""
        INSERT INTO annotation_categories (id, name, label, color, show_on_graph, is_system) VALUES
            (gen_random_uuid(), 'failure',       'Failure',       'red',   true,  false),
            (gen_random_uuid(), 'info',          'Info',          'sky',   true,  false),
            (gen_random_uuid(), 'investigation', 'Investigation', 'amber', true,  false),
            (gen_random_uuid(), 're-evaluation', 'Re-eval',       'gray',  false, true)
        ON CONFLICT (name) DO NOTHING
    """)

    # Seed change point detection defaults.
    op.execute("""
        INSERT INTO configuration (id, name, value, value_type, description) VALUES
            (gen_random_uuid(), 'change_point.enabled',                    'true',  'bool',  'enable change point detection globally'),
            (gen_random_uuid(), 'change_point.window_size',                '30',    'int',   'sliding window length for E-Divisive algorithm'),
            (gen_random_uuid(), 'change_point.max_pvalue',                 '0.001', 'float', 'significance threshold — change points above this are discarded'),
            (gen_random_uuid(), 'change_point.min_magnitude',              '0.0',   'float', 'minimum relative change (fraction) to keep a change point'),
            (gen_random_uuid(), 'change_point.min_sample_size',            '10',    'int',   'skip detection if fewer values than this'),
            (gen_random_uuid(), 'change_point.pvalue_strict_threshold',    '0.05',  'float', 'first-pass relaxation boundary — strict max_pvalue values get 10x relaxation'),
            (gen_random_uuid(), 'change_point.pvalue_moderate_threshold',  '0.5',   'float', 'first-pass relaxation boundary — moderate max_pvalue values get 2x relaxation')
        ON CONFLICT (name) DO NOTHING
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Remove seeded rows (leaves user-created types untouched).
    op.execute("""
        DELETE FROM asset_types
        WHERE name IN ('vm', 'service', 'database', 'container', 'endpoint', 'load-test')
    """)
    op.execute("""
        DELETE FROM annotation_categories
        WHERE name IN ('failure', 'info', 'investigation', 're-evaluation')
    """)
    op.execute("""
        DELETE FROM configuration
        WHERE name LIKE 'change_point.%%'
    """)
    # TimescaleDB hypertables cannot be converted back to plain tables;
    # the table itself is dropped with the schema in migration 1 downgrade.
