"""TimescaleDB hypertable and seed data.

Revision ID: 002
Revises: 001
Create Date: 2026-03-15 20:40:59.384949

Manual migration — not autogenerated.
Converts sli_values to a TimescaleDB hypertable and seeds default asset types.
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: str | Sequence[str] | None = '001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Convert sli_values to a TimescaleDB hypertable partitioned by eval_start.
    # if_not_exists=TRUE makes this safe to re-run.
    op.execute("SELECT create_hypertable('sli_values', 'eval_start', if_not_exists => TRUE)")

    # Seed default asset types.
    # ON CONFLICT DO NOTHING so re-running this migration is idempotent.
    op.execute("""
        INSERT INTO asset_types (id, name, is_default) VALUES
            (gen_random_uuid(), 'vm',        true),
            (gen_random_uuid(), 'service',   false),
            (gen_random_uuid(), 'database',  false),
            (gen_random_uuid(), 'container', false),
            (gen_random_uuid(), 'endpoint',  false),
            (gen_random_uuid(), 'load-test', false)
        ON CONFLICT (name) DO NOTHING
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Remove seeded rows (leaves user-created types untouched).
    op.execute("""
        DELETE FROM asset_types
        WHERE name IN ('vm', 'service', 'database', 'container', 'endpoint', 'load-test')
    """)
    # TimescaleDB hypertables cannot be converted back to plain tables;
    # the table itself is dropped with the schema in migration 1 downgrade.
