"""Domain model redesign — rename columns, add new tables.

Revision ID: 003
Revises: 002
Create Date: 2026-03-14 12:37:02.975218

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "003"
down_revision: str | Sequence[str] | None = "002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "data_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("adapter_type", sa.Text(), nullable=False),
        sa.Column("adapter_url", sa.Text(), nullable=False),
        sa.Column(
            "labels",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("idx_data_sources_name", "data_sources", ["name"], unique=False)
    op.create_table(
        "evaluation_batches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column(
            "trigger_params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "evaluation_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_evaluation_batches_status", "evaluation_batches", ["status"], unique=False)
    op.create_table(
        "sli_definitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "indicators",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", name="uq_sli_name_version"),
    )
    op.create_index(
        "idx_sli_definitions_latest",
        "sli_definitions",
        ["name", sa.literal_column("version DESC")],
        unique=False,
    )
    op.create_index("idx_sli_definitions_name", "sli_definitions", ["name"], unique=False)
    op.create_table(
        "asset_group_links",
        sa.Column("parent_group_id", sa.UUID(), nullable=False),
        sa.Column("child_group_id", sa.UUID(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["child_group_id"], ["asset_groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_group_id"], ["asset_groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("parent_group_id", "child_group_id"),
    )
    op.create_index(
        "idx_asset_group_links_parent", "asset_group_links", ["parent_group_id"], unique=False
    )
    op.create_table(
        "asset_group_members",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["group_id"], ["asset_groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("group_id", "asset_id"),
    )
    op.create_index(
        "idx_asset_group_members_asset", "asset_group_members", ["asset_id"], unique=False
    )
    op.create_index(
        "idx_asset_group_members_group", "asset_group_members", ["group_id"], unique=False
    )
    op.create_table(
        "asset_group_slo_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("link_name", sa.Text(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("slo_name", sa.Text(), nullable=False),
        sa.Column("sli_name", sa.Text(), nullable=False),
        sa.Column("data_source_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["group_id"], ["asset_groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "link_name", name="uq_asset_group_slo_link_name"),
    )
    op.create_index(
        "idx_asset_group_slo_links_group", "asset_group_slo_links", ["group_id"], unique=False
    )
    op.create_table(
        "asset_slo_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("link_name", sa.Text(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("slo_name", sa.Text(), nullable=False),
        sa.Column("sli_name", sa.Text(), nullable=False),
        sa.Column("data_source_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id", "link_name", name="uq_asset_slo_link_name"),
    )
    op.create_index("idx_asset_slo_links_asset", "asset_slo_links", ["asset_id"], unique=False)
    op.add_column("assets", sa.Column("display_name", sa.Text(), nullable=True))
    op.add_column(
        "evaluation_annotations", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column("evaluations", "start_time", new_column_name="period_start")
    op.alter_column("evaluations", "end_time", new_column_name="period_end")
    op.add_column("evaluations", sa.Column("sli_name", sa.Text(), nullable=True))
    op.add_column("evaluations", sa.Column("sli_version", sa.Integer(), nullable=True))
    op.add_column("evaluations", sa.Column("data_source_name", sa.Text(), nullable=True))
    op.drop_index(op.f("idx_evaluations_start"), table_name="evaluations")
    op.create_index("idx_evaluations_start", "evaluations", ["period_start"], unique=False)
    op.drop_index(op.f("sli_values_eval_start_idx"), table_name="sli_values")
    op.add_column("slo_definitions", sa.Column("display_name", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("slo_definitions", "display_name")
    op.create_index(
        op.f("sli_values_eval_start_idx"),
        "sli_values",
        [sa.literal_column("eval_start DESC")],
        unique=False,
    )
    op.drop_index("idx_evaluations_start", table_name="evaluations")
    op.drop_column("evaluations", "data_source_name")
    op.drop_column("evaluations", "sli_version")
    op.drop_column("evaluations", "sli_name")
    op.alter_column("evaluations", "period_end", new_column_name="end_time")
    op.alter_column("evaluations", "period_start", new_column_name="start_time")
    op.create_index(op.f("idx_evaluations_start"), "evaluations", ["start_time"], unique=False)
    op.drop_column("evaluation_annotations", "updated_at")
    op.drop_column("assets", "display_name")
    op.drop_index("idx_asset_slo_links_asset", table_name="asset_slo_links")
    op.drop_table("asset_slo_links")
    op.drop_index("idx_asset_group_slo_links_group", table_name="asset_group_slo_links")
    op.drop_table("asset_group_slo_links")
    op.drop_index("idx_asset_group_members_group", table_name="asset_group_members")
    op.drop_index("idx_asset_group_members_asset", table_name="asset_group_members")
    op.drop_table("asset_group_members")
    op.drop_index("idx_asset_group_links_parent", table_name="asset_group_links")
    op.drop_table("asset_group_links")
    op.drop_index("idx_sli_definitions_name", table_name="sli_definitions")
    op.drop_index("idx_sli_definitions_latest", table_name="sli_definitions")
    op.drop_table("sli_definitions")
    op.drop_index("idx_evaluation_batches_status", table_name="evaluation_batches")
    op.drop_table("evaluation_batches")
    op.drop_index("idx_data_sources_name", table_name="data_sources")
    op.drop_table("data_sources")
    op.drop_table("asset_groups")
    # ### end Alembic commands ###
