"""003_baseline_pin_and_override.

Revision ID: 27d4e408fa6f
Revises: 002
Create Date: 2026-03-17 11:00:39.425793

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "27d4e408fa6f"
down_revision: str | Sequence[str] | None = "002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("evaluation_batches", sa.Column("result", sa.Text(), nullable=True))
    op.add_column("evaluation_batches", sa.Column("score", sa.Float(), nullable=True))
    op.add_column(
        "evaluation_batches",
        sa.Column("rollup_details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "evaluations", sa.Column("baseline_pinned_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "evaluations", sa.Column("baseline_unpinned_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("evaluations", sa.Column("baseline_pin_reason", sa.Text(), nullable=True))
    op.add_column("evaluations", sa.Column("baseline_pin_author", sa.Text(), nullable=True))
    op.add_column("evaluations", sa.Column("original_result", sa.Text(), nullable=True))
    op.add_column("evaluations", sa.Column("override_reason", sa.Text(), nullable=True))
    op.add_column("evaluations", sa.Column("override_author", sa.Text(), nullable=True))

    # Enforce single active pin per (asset_id, slo_name)
    op.create_index(
        "uq_evaluations_active_pin",
        "evaluations",
        ["asset_id", "slo_name"],
        unique=True,
        postgresql_where=sa.text("baseline_pinned_at IS NOT NULL AND baseline_unpinned_at IS NULL"),
    )

    # Check constraint on original_result — same enum as result
    op.create_check_constraint(
        "ck_evaluations_original_result",
        "evaluations",
        "original_result IN ('pass', 'warning', 'fail', 'error') OR original_result IS NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_evaluations_original_result", "evaluations", type_="check")
    op.drop_index("uq_evaluations_active_pin", table_name="evaluations")
    op.drop_column("evaluations", "override_author")
    op.drop_column("evaluations", "override_reason")
    op.drop_column("evaluations", "original_result")
    op.drop_column("evaluations", "baseline_pin_author")
    op.drop_column("evaluations", "baseline_pin_reason")
    op.drop_column("evaluations", "baseline_unpinned_at")
    op.drop_column("evaluations", "baseline_pinned_at")
    op.drop_column("evaluation_batches", "rollup_details")
    op.drop_column("evaluation_batches", "score")
    op.drop_column("evaluation_batches", "result")
    # ### end Alembic commands ###
