"""slo_format_redesign.

Revision ID: 63404ff4de0e
Revises: 002
Create Date: 2026-03-15 22:53:39.527263

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "63404ff4de0e"
down_revision: str | Sequence[str] | None = "002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: This is a clean-break migration. No data migration for slo_yaml.
    # If you have existing slo_definitions rows, truncate them before running.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slo_objectives",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slo_definition_id", sa.UUID(), nullable=False),
        sa.Column("sli", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), server_default="", nullable=False),
        sa.Column("weight", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("key_sli", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "pass_criteria", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column(
            "warning_criteria", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.ForeignKeyConstraint(["slo_definition_id"], ["slo_definitions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_slo_objectives_definition", "slo_objectives", ["slo_definition_id"], unique=False
    )
    op.drop_column("evaluations", "slo_yaml")
    op.drop_index(op.f("sli_values_eval_start_idx"), table_name="sli_values")
    op.add_column(
        "slo_definitions",
        sa.Column(
            "total_score_pass_pct", sa.Float(), server_default=sa.text("90.0"), nullable=False
        ),
    )
    op.add_column(
        "slo_definitions",
        sa.Column(
            "total_score_warning_pct", sa.Float(), server_default=sa.text("75.0"), nullable=False
        ),
    )
    op.add_column(
        "slo_definitions",
        sa.Column(
            "comparison",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.drop_column("slo_definitions", "slo_yaml")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "slo_definitions", sa.Column("slo_yaml", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.drop_column("slo_definitions", "comparison")
    op.drop_column("slo_definitions", "total_score_warning_pct")
    op.drop_column("slo_definitions", "total_score_pass_pct")
    op.create_index(
        op.f("sli_values_eval_start_idx"),
        "sli_values",
        [sa.literal_column("eval_start DESC")],
        unique=False,
    )
    op.add_column(
        "evaluations", sa.Column("slo_yaml", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_index("idx_slo_objectives_definition", table_name="slo_objectives")
    op.drop_table("slo_objectives")
    # ### end Alembic commands ###
