"""Repository for SLO groups."""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from typing import Any

from sqlalchemy import func, select, true
from sqlalchemy.ext.asyncio import AsyncSession

from tropek.db.models import (
    SLODefinition,
    SLOGroup,
)

_UNSET: Any = object()  # sentinel — distinguishes "not provided" from None


class SLOGroupRepository:
    """CRUD for slo_groups table."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(
        self,
        *,
        name: str,
        display_name: str | None = None,
        template_slo_definition_id: uuid.UUID,
        gen_variables: dict[str, list[str]],
        tags: dict[str, Any] | None = None,
        author: str | None = None,
    ) -> SLOGroup:
        """Insert a new SLO group row and return it."""
        group = SLOGroup(
            id=uuid.uuid4(),
            name=name,
            display_name=display_name,
            template_slo_definition_id=template_slo_definition_id,
            gen_variables=gen_variables,
            tags=tags or {},
            author=author,
        )
        self._session.add(group)
        await self._session.flush()
        return group

    async def get_by_name(self, name: str) -> SLOGroup | None:
        """Return the active group with the given name, or None."""
        result = await self._session.execute(select(SLOGroup).where(SLOGroup.name == name, SLOGroup.active == true()))
        return result.scalar_one_or_none()

    async def get_by_id(self, group_id: uuid.UUID) -> SLOGroup | None:
        """Return the group with the given primary key, or None."""
        result = await self._session.execute(select(SLOGroup).where(SLOGroup.id == group_id))
        return result.scalar_one_or_none()

    async def list_all(
        self,
        *,
        tag_key: str | None = None,
        tag_val: str | None = None,
    ) -> list[SLOGroup]:
        """Return all active groups, optionally filtered by a tag key/value pair."""
        q = select(SLOGroup).where(SLOGroup.active == true())
        if tag_key and tag_val:
            q = q.where(SLOGroup.tags[tag_key].astext == tag_val)
        elif tag_key:
            q = q.where(SLOGroup.tags.has_key(tag_key))
        return list((await self._session.execute(q.order_by(SLOGroup.name))).scalars().all())

    async def update(
        self,
        name: str,
        *,
        template_slo_definition_id: uuid.UUID | None = None,
        gen_variables: dict[str, list[str]] | None = None,
        display_name: Any = _UNSET,
        tags: dict[str, Any] | None = None,
        author: Any = _UNSET,
    ) -> SLOGroup | None:
        """Update mutable fields on an active group; bumps version. Returns None if not found."""
        group = await self.get_by_name(name)
        if group is None:
            return None
        if template_slo_definition_id is not None:
            group.template_slo_definition_id = template_slo_definition_id
        if gen_variables is not None:
            group.gen_variables = gen_variables
        if display_name is not _UNSET:
            group.display_name = display_name
        if tags is not None:
            group.tags = tags
        if author is not _UNSET:
            group.author = author
        group.version += 1
        group.updated_at = datetime.now(UTC)
        await self._session.flush()
        return group

    async def deactivate(self, name: str) -> None:
        """Mark the group as inactive (soft delete). No-op if not found."""
        group = await self.get_by_name(name)
        if group is None:
            return
        group.active = False
        group.updated_at = datetime.now(UTC)
        await self._session.flush()

    async def count_generated_slos(self, group_id: uuid.UUID) -> int:
        """Return the count of distinct active SLO names generated by the given group."""
        result = await self._session.execute(
            select(func.count(func.distinct(SLODefinition.name)))
            .select_from(SLODefinition)
            .where(SLODefinition.generated_by_group_id == group_id, SLODefinition.active == true())
        )
        return result.scalar_one()
