"""Stateful Schemathesis tests — chain requests to catch state-dependent bugs.

The state machine is generated from OpenAPI operation links. FastAPI does not
emit links by default, so the generated sequences are currently minimal — this
test is scaffolding for when explicit links are added to the schema.
"""

from __future__ import annotations

import pytest

from tests.schemathesis.conftest import schema


@pytest.mark.schemathesis
class TestAPIStateMachine(schema.as_state_machine()):  # type: ignore[misc]
    """Exercise realistic request sequences generated by the state machine."""
