"""Single Schemathesis entry point — expands into hundreds of generated cases."""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

import pytest
from hypothesis import settings
from schemathesis import Case, checks
from schemathesis.specs.openapi.checks import positive_data_acceptance

from tests.schemathesis.conftest import schema

CheckFunction = Callable[..., Any]

# Activate the full check set — conformance (status code, content type, schema)
# plus security-oriented checks: ``negative_data_rejection`` and
# ``positive_data_acceptance`` fuzz string params with SQLi / path-traversal /
# XSS payloads, while ``not_a_server_error`` catches unhandled 500s that reveal
# validation gaps. ``validate_response`` uses the registered set when invoked
# without an explicit ``checks=`` argument.
checks.load_all_checks()

# Endpoints excluded from fuzzing entirely because they have production-style
# side effects (enqueue arq worker jobs) that should not be triggered by
# property-based synthetic inputs.  Schemathesis generates structurally-valid
# inputs, but the underlying domain ("no SLO assignments found for asset ''")
# always rejects them, producing false-positive RejectedPositiveData failures
# that are inherent to stateless fuzzing of stateful domain endpoints.
EXCLUDED_OPERATIONS: set[tuple[str, str]] = {
    # Trigger endpoints — enqueue arq worker jobs; require pre-existing
    # asset+SLO assignment data that schemathesis cannot set up.
    ('POST', '/evaluations'),
    ('POST', '/evaluations/batch'),
    # Re-evaluate endpoints — trigger re-scoring with DB side effects;
    # same "no SLO assignments found" domain rejection as above.
    ('POST', '/evaluations/re-evaluate/from-date'),
    ('POST', '/evaluations/re-evaluate/from-baseline'),
    ('POST', '/evaluations/re-evaluate/from-evaluation/{evaluation_id}'),
    # SLO groups require an existing template SLO; empty-name inputs always
    # trigger "template slo '' not found" domain validation.
    ('POST', '/slo-groups'),
    # PATCH /asset-types/{name} requires name in body (domain validation),
    # but all PATCH body fields are schema-optional. The {} empty body is
    # schema-compliant but always rejected — this is an unrepresentable
    # min-properties constraint not expressible in JSON Schema.
    ('PATCH', '/asset-types/{name}'),
}

# Operations excluded from specific checks only.
# All other checks remain active (status codes, response schema, server errors).
#
#   POST /sli-definitions — adapter_type-specific mode fields (raw vs aggregated)
#       are a cross-field constraint enforced by @model_validator. The open
#       adapter plugin registry makes it impossible to express mode-specific
#       field requirements in a static OpenAPI schema — adapters are discovered
#       at runtime and may extend the field set. Excluding only
#       positive_data_acceptance keeps all other conformance checks active.
#
#   GET /assets/.../meta/snapshots — "from must be before or equal to to"
#       cross-field validation on query params not expressible in OpenAPI.
#
#   GET /assets/.../meta/timeline* — "from must be before to" cross-field
#       validation on equal timestamps generated by schemathesis.
#
#   POST /assets/{asset_id}/meta/snapshots — values-or-closed XOR: the body
#       must have non-empty `values` or non-empty `closed`, but not both empty.
#       This is a cross-field constraint unrepresentable in OpenAPI 3.1.
#
#   POST /slo-definitions — objective.sli must reference a key in the SLI
#       definition's indicators dict. Cross-field constraint between parent and
#       child objects.
#
#   POST /slo-definitions/test — dry-run evaluation requires existing datasource,
#       SLI definition, and asset. Cross-resource data dependency.
#
#   GET /evaluations — date and from/to query params are mutually exclusive.
#       OpenAPI 3.1 has no `oneOf` for query parameter groups.
#
#   POST /assets, PATCH /assets/{name} — heatmap_config is an opaque
#       dict[str, Any] with no UI consumer or agreed shape. Null bytes in
#       deeply nested keys are rejected server-side but the constraint is not
#       expressible in OpenAPI.
#
#   POST /slo-display-groups — parent_id is a self-referential FK.
#       Schemathesis generates random UUIDs that don't reference existing
#       groups, causing FK violations (409). Data-dependency constraint.
#
#   PATCH /assets/{name}/slo-assignments/{assignment_id} — new_slo_definition_id
#       must reference an existing SLO definition. Cross-resource FK dependency.
#
#   POST /slo-definitions/validate — same change_point nested-object constraint
#       as POST /slo-definitions.
#
#   GET /change-points — fuzzed datetime query params rejected by domain validation.
#
#   PUT /change-points/config/{objective_id} — StrictInput body; fuzzed numeric
#       fields (pvalue, magnitude) rejected by domain-range validation.
#
#   PATCH /change-points/{change_point_id} — StrictInput triage body; fuzzed
#       status values rejected by domain validation.
EXCLUDED_CHECKS_PER_OP: dict[tuple[str, str], list[CheckFunction]] = {
    ('POST', '/sli-definitions'): [positive_data_acceptance],
    ('GET', '/assets/{asset_id}/meta/snapshots'): [positive_data_acceptance],
    ('GET', '/assets/{asset_id}/meta/timeline'): [positive_data_acceptance],
    ('GET', '/assets/{asset_id}/meta/timeline/summary'): [positive_data_acceptance],
    ('POST', '/assets/{asset_id}/meta/snapshots'): [positive_data_acceptance],
    ('POST', '/slo-definitions'): [positive_data_acceptance],
    ('POST', '/slo-definitions/validate'): [positive_data_acceptance],
    ('POST', '/slo-definitions/test'): [positive_data_acceptance],
    ('GET', '/change-points'): [positive_data_acceptance],
    ('PUT', '/change-points/config/{objective_id}'): [positive_data_acceptance],
    ('PATCH', '/change-points/{change_point_id}'): [positive_data_acceptance],
    #   GET /change-points/{change_point_id} — random UUID never matches an existing row.
    ('GET', '/change-points/{change_point_id}'): [positive_data_acceptance],
    #   PATCH /change-points/bulk-triage — StrictInput body; fuzzed UUIDs and
    #       status values rejected by domain validation.
    ('PATCH', '/change-points/bulk-triage'): [positive_data_acceptance],
    ('GET', '/evaluations'): [positive_data_acceptance],
    ('POST', '/assets'): [positive_data_acceptance],
    ('PATCH', '/assets/{name}'): [positive_data_acceptance],
    ('POST', '/slo-display-groups'): [positive_data_acceptance],
    ('PATCH', '/assets/{name}/slo-assignments/{assignment_id}'): [positive_data_acceptance],
    #   GET /configuration — null-byte prefix values in fuzzed query params crash
    #       the asyncpg driver. No user-facing query params to validate.
    ('GET', '/configuration'): [positive_data_acceptance],
}


@pytest.mark.schemathesis
@schema.parametrize()
@settings(max_examples=50)
def test_api_conforms_to_schema(case: Case) -> None:
    """Verify every (method, path) pair returns responses conforming to the spec."""
    key = (case.method.upper(), case.path)
    if key in EXCLUDED_OPERATIONS:
        pytest.skip('excluded from fuzzing (side-effect-heavy or unrepresentable-constraint endpoint)')

    excluded_checks = EXCLUDED_CHECKS_PER_OP.get(key, [])

    response = case.call()
    case.validate_response(response, excluded_checks=excluded_checks)
