"""Single Schemathesis entry point — expands into hundreds of generated cases."""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

import pytest
from schemathesis import Case, checks
from schemathesis.specs.openapi.checks import positive_data_acceptance

from tests.schemathesis.conftest import schema

CheckFunction = Callable[..., Any]

# Activate the full check set — conformance (status code, content type, schema)
# plus security-oriented checks: ``negative_data_rejection`` and
# ``positive_data_acceptance`` fuzz string params with SQLi / path-traversal /
# XSS payloads, while ``not_a_server_error`` catches unhandled 500s that reveal
# validation gaps. ``validate_response`` uses the registered set when invoked
# without an explicit ``checks=`` argument.
checks.load_all_checks()

# Endpoints excluded from fuzzing entirely because they have production-style
# side effects (enqueue arq worker jobs) that should not be triggered by
# property-based synthetic inputs.  Schemathesis generates structurally-valid
# inputs, but the underlying domain ("no SLO assignments found for asset ''")
# always rejects them, producing false-positive RejectedPositiveData failures
# that are inherent to stateless fuzzing of stateful domain endpoints.
EXCLUDED_OPERATIONS: set[tuple[str, str]] = {
    # Trigger endpoints — enqueue arq worker jobs; require pre-existing
    # asset+SLO assignment data that schemathesis cannot set up.
    ('POST', '/evaluations'),
    ('POST', '/evaluations/batch'),
    # Re-evaluate endpoints — trigger re-scoring with DB side effects;
    # same "no SLO assignments found" domain rejection as above.
    ('POST', '/evaluations/re-evaluate/from-date'),
    ('POST', '/evaluations/re-evaluate/from-baseline'),
    ('POST', '/evaluations/re-evaluate/from-evaluation/{evaluation_id}'),
    # SLO groups require an existing template SLO; empty-name inputs always
    # trigger "template slo '' not found" domain validation.
    ('POST', '/slo-groups'),
    # PATCH /asset-types/{name} requires name in body (domain validation),
    # but all PATCH body fields are schema-optional. The {} empty body is
    # schema-compliant but always rejected — this is an unrepresentable
    # min-properties constraint not expressible in JSON Schema.
    ('PATCH', '/asset-types/{name}'),
}

# Operations excluded from specific checks only.
# All other checks remain active (status codes, response schema, server errors).
#
#   POST /sli-definitions — adapter_type-specific mode fields (raw vs aggregated)
#       are a cross-field constraint enforced by @model_validator. The open
#       adapter plugin registry makes it impossible to express mode-specific
#       field requirements in a static OpenAPI schema — adapters are discovered
#       at runtime and may extend the field set. Excluding only
#       positive_data_acceptance keeps all other conformance checks active.
#
#   GET /assets/.../meta/timeline* — "from must be before to" cross-field
#       validation on equal timestamps generated by schemathesis.
EXCLUDED_CHECKS_PER_OP: dict[tuple[str, str], list[CheckFunction]] = {
    ('POST', '/sli-definitions'): [positive_data_acceptance],
    ('GET', '/assets/{asset_id}/meta/timeline'): [positive_data_acceptance],
    ('GET', '/assets/{asset_id}/meta/timeline/summary'): [positive_data_acceptance],
}


@pytest.mark.schemathesis
@schema.parametrize()
def test_api_conforms_to_schema(case: Case) -> None:
    """Verify every (method, path) pair returns responses conforming to the spec."""
    key = (case.method.upper(), case.path)
    if key in EXCLUDED_OPERATIONS:
        pytest.skip('excluded from fuzzing (side-effect-heavy or unrepresentable-constraint endpoint)')

    excluded_checks = EXCLUDED_CHECKS_PER_OP.get(key, [])

    response = case.call()
    case.validate_response(response, excluded_checks=excluded_checks)
