"""Repositories for SLO groups and template bindings."""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from typing import Any

from sqlalchemy import delete, func, or_, select, true
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.models import (
    SLODefinition,
    SLOGroup,
    TemplateBinding,
)

_UNSET: Any = object()  # sentinel — distinguishes "not provided" from None


class SLOGroupRepository:
    """CRUD for slo_groups table."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(
        self,
        *,
        name: str,
        display_name: str | None = None,
        template_slo_name: str,
        template_slo_version: int,
        gen_variables: dict[str, list[str]],
        tags: dict[str, Any] | None = None,
        author: str | None = None,
    ) -> SLOGroup:
        """Insert a new SLO group row and return it."""
        group = SLOGroup(
            id=uuid.uuid4(),
            name=name,
            display_name=display_name,
            template_slo_name=template_slo_name,
            template_slo_version=template_slo_version,
            gen_variables=gen_variables,
            tags=tags or {},
            author=author,
        )
        self._session.add(group)
        await self._session.flush()
        return group

    async def get_by_name(self, name: str) -> SLOGroup | None:
        """Return the active group with the given name, or None."""
        result = await self._session.execute(select(SLOGroup).where(SLOGroup.name == name, SLOGroup.active == true()))
        return result.scalar_one_or_none()

    async def get_by_id(self, group_id: uuid.UUID) -> SLOGroup | None:
        """Return the group with the given primary key, or None."""
        result = await self._session.execute(select(SLOGroup).where(SLOGroup.id == group_id))
        return result.scalar_one_or_none()

    async def list_all(
        self,
        *,
        tag_key: str | None = None,
        tag_val: str | None = None,
    ) -> list[SLOGroup]:
        """Return all active groups, optionally filtered by a tag key/value pair."""
        q = select(SLOGroup).where(SLOGroup.active == true())
        if tag_key and tag_val:
            q = q.where(SLOGroup.tags[tag_key].astext == tag_val)
        elif tag_key:
            q = q.where(SLOGroup.tags.has_key(tag_key))
        return list((await self._session.execute(q.order_by(SLOGroup.name))).scalars().all())

    async def update(
        self,
        name: str,
        *,
        template_slo_name: str | None = None,
        template_slo_version: int | None = None,
        gen_variables: dict[str, list[str]] | None = None,
        display_name: Any = _UNSET,
        tags: dict[str, Any] | None = None,
    ) -> SLOGroup | None:
        """Update mutable fields on an active group; bumps version. Returns None if not found."""
        group = await self.get_by_name(name)
        if group is None:
            return None
        if template_slo_name is not None:
            group.template_slo_name = template_slo_name
        if template_slo_version is not None:
            group.template_slo_version = template_slo_version
        if gen_variables is not None:
            group.gen_variables = gen_variables
        if display_name is not _UNSET:
            group.display_name = display_name
        if tags is not None:
            group.tags = tags
        group.version += 1
        group.updated_at = datetime.now(UTC)
        await self._session.flush()
        return group

    async def deactivate(self, name: str) -> None:
        """Mark the group as inactive (soft delete). No-op if not found."""
        group = await self.get_by_name(name)
        if group is None:
            return
        group.active = False
        group.updated_at = datetime.now(UTC)
        await self._session.flush()

    async def list_groups_by_template(self, template_slo_name: str) -> list[SLOGroup]:
        """Return all active groups that reference the given template SLO name."""
        result = await self._session.execute(
            select(SLOGroup).where(
                SLOGroup.template_slo_name == template_slo_name,
                SLOGroup.active == true(),
            )
        )
        return list(result.scalars().all())

    async def count_generated_slos(self, group_id: uuid.UUID) -> int:
        """Return the count of distinct active SLO names generated by the given group."""
        result = await self._session.execute(
            select(func.count(func.distinct(SLODefinition.name)))
            .select_from(SLODefinition)
            .where(SLODefinition.generated_by_group_id == group_id, SLODefinition.active == true())
        )
        return result.scalar_one()


class TemplateBindingRepository:
    """CRUD for template_bindings polymorphic table."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(
        self,
        *,
        target_type: str,
        target_id: uuid.UUID,
        template_group_name: str,
        data_source_name: str,
    ) -> TemplateBinding:
        """Insert a new template binding row and return it."""
        binding = TemplateBinding(
            id=uuid.uuid4(),
            target_type=target_type,
            target_id=target_id,
            template_group_name=template_group_name,
            data_source_name=data_source_name,
        )
        self._session.add(binding)
        await self._session.flush()
        return binding

    async def list_by_target(
        self,
        target_type: str,
        target_id: uuid.UUID,
    ) -> list[TemplateBinding]:
        """Return all bindings for a given target type and ID, ordered by group name."""
        result = await self._session.execute(
            select(TemplateBinding)
            .where(TemplateBinding.target_type == target_type, TemplateBinding.target_id == target_id)
            .order_by(TemplateBinding.template_group_name)
        )
        return list(result.scalars().all())

    async def list_by_group_name(self, template_group_name: str) -> list[TemplateBinding]:
        """Return all bindings that reference the given template group name."""
        result = await self._session.execute(
            select(TemplateBinding).where(TemplateBinding.template_group_name == template_group_name)
        )
        return list(result.scalars().all())

    async def list_for_asset_evaluation(
        self,
        asset_id: uuid.UUID,
        group_ids: list[uuid.UUID],
    ) -> list[TemplateBinding]:
        """Collect all template bindings relevant to an asset: direct + via groups."""
        conditions = [
            (TemplateBinding.target_type == 'asset') & (TemplateBinding.target_id == asset_id),
        ]
        if group_ids:
            conditions.append(
                (TemplateBinding.target_type == 'asset_group') & (TemplateBinding.target_id.in_(group_ids))
            )
        result = await self._session.execute(
            select(TemplateBinding).where(or_(*conditions)).order_by(TemplateBinding.template_group_name)
        )
        return list(result.scalars().all())

    async def delete_by_target_and_group(
        self,
        target_type: str,
        target_id: uuid.UUID,
        template_group_name: str,
    ) -> None:
        """Delete the specific binding matching target type, target ID, and group name."""
        await self._session.execute(
            delete(TemplateBinding).where(
                TemplateBinding.target_type == target_type,
                TemplateBinding.target_id == target_id,
                TemplateBinding.template_group_name == template_group_name,
            )
        )

    async def delete_all_by_group(self, template_group_name: str) -> None:
        """Delete all bindings that reference the given template group name."""
        await self._session.execute(
            delete(TemplateBinding).where(TemplateBinding.template_group_name == template_group_name)
        )
