#!/usr/bin/env bash
# db-regen-migrations.sh
#
# Squashes all Alembic migrations into a single autogenerated 001 + the manual
# 002 (TimescaleDB hypertable + seed data).  Intended for rapid-prototyping
# phases where no one is running the software and the migration history can be
# rewritten freely.
#
# What it does:
#   1. Tears down the test DB (empty slate).
#   2. Moves 002 aside, deletes everything else in versions/.
#   3. Starts the test DB (empty, no migrations applied).
#   4. Autogenerates a fresh migration from current SQLAlchemy models.
#   5. Renames the autogenerated file to 001_initial_schema.py (revision "001").
#   6. Restores 002_timescaledb_hypertable_and_seed_data.py.
#   7. Tears down and restarts test DB to verify both migrations apply cleanly.
#
# Prerequisites:
#   - .env.test exists (copy from .env.test.example)
#   - Docker is running
#   - uv is installed
#
# Usage:
#   ./scripts/db-regen-migrations.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
VERSIONS_DIR="${REPO_ROOT}/api/alembic/versions"
MANUAL_002="${VERSIONS_DIR}/002_timescaledb_hypertable_and_seed_data.py"
MANUAL_002_BAK="${MANUAL_002}.bak"

# ── Preflight checks ────────────────────────────────────────────────────────
if [[ ! -f "${REPO_ROOT}/.env.test" ]]; then
    echo "ERROR: .env.test not found. Copy .env.test.example and fill in values." >&2
    exit 1
fi

if [[ ! -f "${MANUAL_002}" ]]; then
    echo "ERROR: ${MANUAL_002} not found — cannot proceed." >&2
    exit 1
fi

# ── Step 1: Tear down test infrastructure ────────────────────────────────────
echo "==> Step 1: Tearing down test infrastructure..."
"${REPO_ROOT}/stop_test_infra.sh"

# ── Step 2: Backup 002 and clear versions/ ───────────────────────────────────
echo ""
echo "==> Step 2: Backing up 002 and clearing migration files..."
cp "${MANUAL_002}" "${MANUAL_002_BAK}"

# Remove all .py files in versions/ (migrations + any leftover __pycache__)
find "${VERSIONS_DIR}" -maxdepth 1 -name "*.py" -delete
rm -rf "${VERSIONS_DIR}/__pycache__"

echo "    Backed up 002 to ${MANUAL_002_BAK##*/}"

# ── Step 3: Start test DB (empty, no migrations) ────────────────────────────
echo ""
echo "==> Step 3: Starting test DB (empty)..."
"${REPO_ROOT}/start_test_infra.sh"

# ── Step 4: Autogenerate fresh migration from models ────────────────────────
echo ""
echo "==> Step 4: Autogenerating migration from current models..."
ENV_FILE="${REPO_ROOT}/.env.test" uv run --directory "${REPO_ROOT}/api" \
    alembic revision --autogenerate -m "initial schema"

# Find the generated file (the only .py in versions/ now)
GENERATED_FILE=$(find "${VERSIONS_DIR}" -maxdepth 1 -name "*.py" -print -quit)
if [[ -z "${GENERATED_FILE}" ]]; then
    echo "ERROR: autogenerate produced no migration file." >&2
    mv "${MANUAL_002_BAK}" "${MANUAL_002}"
    exit 1
fi

echo "    Generated: ${GENERATED_FILE##*/}"

# ── Step 5: Rename to 001 and fix revision ID ───────────────────────────────
echo ""
echo "==> Step 5: Renaming to 001_initial_schema.py..."
NEW_001="${VERSIONS_DIR}/001_initial_schema.py"
mv "${GENERATED_FILE}" "${NEW_001}"

# Extract the autogenerated hash revision from the file
OLD_REV=$(grep -oP "^revision: str = ['\"]\\K[^'\"]+" "${NEW_001}")
if [[ -n "${OLD_REV}" ]]; then
    sed -i "s|Revision ID: ${OLD_REV}|Revision ID: 001|" "${NEW_001}"
    sed -i "s|revision: str = ['\"]${OLD_REV}['\"]|revision: str = \"001\"|" "${NEW_001}"
    echo "    Replaced revision ${OLD_REV} -> 001"
else
    echo "WARNING: could not find revision hash in generated file." >&2
fi

# ── Step 6: Restore 002 ─────────────────────────────────────────────────────
echo ""
echo "==> Step 6: Restoring 002_timescaledb_hypertable_and_seed_data.py..."
mv "${MANUAL_002_BAK}" "${MANUAL_002}"

# ── Step 7: Verify — tear down and rebuild from scratch ──────────────────────
echo ""
echo "==> Step 7: Verifying — clean restart with both migrations..."
"${REPO_ROOT}/stop_test_infra.sh"
"${REPO_ROOT}/start_test_infra.sh"

echo ""
echo "==> Migration regeneration complete."
echo "    001_initial_schema.py — autogenerated from current models"
echo "    002_timescaledb_hypertable_and_seed_data.py — restored (manual)"
echo ""
echo "    Run integration tests to verify:"
echo "      uv run pytest api/tests/ -m integration -v"
