apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 30s

  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: tropek
      defaultBucket: slo_metrics
    secureJsonData:
      token: tropek-dev-token

  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb-metrics:5432
    database: slo_metrics
    user: metrics
    secureJsonData:
      password: metrics
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
