apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 30s

  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: slo_metrics
    jsonData:
      version: InfluxQL
      organization: tropek
      httpMode: POST
      httpHeaderName1: Authorization
    secureJsonData:
      httpHeaderValue1: Token tropek-dev-token

  - name: TimescaleDB
    uid: timescaledb
    type: grafana-postgresql-datasource
    access: proxy
    url: timescaledb-metrics:5432
    user: metrics
    secureJsonData:
      password: metrics
    jsonData:
      database: slo_metrics
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
